language: node_js
node_js: "8.11.3"
branches:
  only:
   - master
   - /^v.*$/
cache: yarn
before_install:
  - openssl aes-256-cbc -K $encrypted_48bfcff1b99c_key -iv $encrypted_48bfcff1b99c_iv -in id_rsa_ornamentum.enc -out ~/.ssh/id_rsa_ornamentum -d
install:
  - yarn
  - eval "$(ssh-agent)"
  - chmod 600 ./deploy.secret.key
  - ssh-add ./deploy.secret.key
  - echo $DEPLOY_KNOWN_HOST | base64 --decode >> $HOME/.ssh/known_hosts
  - chmod 644 $HOME/.ssh/known_hosts
script: yarn build
deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.sh"
