sudo: required
language: node_js
node_js: 8.11.3
services:
  - docker
branches:
  only:
  - master
  - "/^v.*$/"
cache: yarn
before_install:
  - "./scripts/before-install.sh"
install:
  - "./scripts/install.sh"
script: yarn build
deploy:
  skip_cleanup: true
  provider: script
  script: "./scripts/deploy.sh"
#  on:
#    tags: true
