language: node_js
node_js: "8.11.3"
branches:
  only:
   - master
   - /^v.*$/
cache: yarn
install: yarn
script: yarn build
addons:
  ssh_known_hosts: ${DEPLOY_HOST}
deploy:
  skip_cleanup: true
  provider: script
  script: /bin/sh /deploy.sh
