#########################
## Sass Lint File
#########################
# Linter Options

files:
  include: 'projects/ornamentum/**/*.scss'
  ignore: 'node_modules/src/**/*'

rules:
  indentation:
    - 0
  leading-zero:
    - 1
    - include: true
  no-duplicate-properties:
    - 0
  nesting-depth:
    - 1
    - max-depth: 5
