#########################
## Sass Lint File
#########################
# Linter Options

files:
  include: 'src/**/*.scss'
  ignore: 'node_modules/**/*'

rules:

  no-duplicate-properties:
    - 0

  nesting-depth:
    - 1
    - max-depth: 5
